name: CI

on:

  push:
    branchaes: [ "main" ]
  pull_request:
    branchaes: [ "main" ]
    
jobs:
  
  my_build_job:
  runs-on: ubuntu-latest
  - uses: action/checkout@v3
  
  - name: npm install, test and build
    run:
      npm install
      npm run build
      
  - name: Run a one-line script
    run: echo Hello, world!
    
  - name: Run a multi-line script
    run:
      echo Add other action to biuld
      echo test, and deploy your project.
  
  - name: Run JS file for test
    run: node script.js
